# Site settings
title: Dmitry Fedosov
email: dimafeng@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This blog is about programming tricks and tips.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://dimafeng.com"
twitter_username: dimafeng
github_username:  dimafeng

# Build settings
markdown: kramdown

permalink: /blog/:year/:month/:day/:title/
